from __future__ import annotations

from .api import compute_test_metrics
from .formatter import format_ab_metrics
from .parallel import parallel_compute_metrics, parallel_compute_metrics_from_sql
from .bootstrap import (
    _apply_multiple_comparisons_adjustment,
    _compute_bootstrap_family_max_statistics,
    _compute_bootstrap_family_max_statistics_batch,
    _compute_bootstrap_family_max_statistics_in_executor,
    _compute_bootstrap_statistics,
    _compute_bootstrap_statistics_batch,
    _compute_bootstrap_statistics_in_executor,
    _compute_mean_delta_from_arrays,
    _compute_metric_family_max_statistics_from_indices,
    _compute_metric_family_statistics_from_indices,
    _compute_metric_statistic_and_delta_from_indices,
    _compute_metric_test_statistic_from_indices,
    _extend_bootstrap_statistics,
    _prepare_bootstrap_context,
    _split_resamples_into_batches,
)
from .constants import DEFAULT_ALPHA, DEFAULT_POWER
from .cuped import (
    _build_cuped_frame,
    _build_metric_values_by_user,
    _compute_cuped_p_value,
    _compute_cuped_p_value_from_frame,
    _compute_cuped_statistics,
    _compute_cuped_statistics_from_frame,
)
from .outliers import (
    _apply_outliers_to_agg_ratio_components,
    _apply_outliers_to_values,
    _build_agg_ratio_outlier_mask,
    _build_outlier_context,
    _build_outlier_contexts,
    _build_value_outlier_mask,
    _compute_outlier_cutoff,
    _count_outliers_by_group,
    _get_outlier_cutoff,
)
from .ratio import (
    _build_agg_ratio_linearized_values,
    _build_ratio_frame_from_arrays,
    _build_ratio_valid_mask,
    _build_ratio_valid_mask_from_arrays,
    _compute_agg_ratio_diff_standard_error,
    _compute_agg_ratio_group_stats,
    _compute_agg_ratio_group_stats_arrays,
    _compute_agg_ratio_variance,
    _normalize_ratio_metrics,
    _require_ratio_spec_value,
)
from .rows import (
    _build_comparisons,
    _build_mean_metric_row,
    _build_metric_definitions,
    _build_metric_row,
    _build_ratio_metric_row,
)
from .stats import (
    _both_present,
    _compute_group_diff_standard_error,
    _compute_mde_abs,
    _compute_mde_from_standard_error,
    _compute_normal_p_value,
    _compute_sample_variance,
    _compute_studentized_statistic,
    _compute_ttest_stat_and_p_value,
    _compute_ttest_stat_and_p_value_arrays,
    _get_numeric_metric_series,
    _safe_mean,
    _safe_relative,
)
from .validation import (
    _validate_input_columns,
    _validate_mde_parameters,
    _validate_multiple_comparisons_parameters,
    _validate_outlier_parameters,
    _validate_pre_experiment_dataframe,
)

__all__ = [
    "DEFAULT_ALPHA",
    "DEFAULT_POWER",
    "compute_test_metrics",
    "format_ab_metrics",
    "parallel_compute_metrics",
    "parallel_compute_metrics_from_sql",
    "_apply_multiple_comparisons_adjustment",
    "_apply_outliers_to_agg_ratio_components",
    "_apply_outliers_to_values",
    "_build_agg_ratio_linearized_values",
    "_build_agg_ratio_outlier_mask",
    "_build_comparisons",
    "_build_cuped_frame",
    "_build_mean_metric_row",
    "_build_metric_definitions",
    "_build_metric_row",
    "_build_outlier_context",
    "_build_outlier_contexts",
    "_build_metric_values_by_user",
    "_build_ratio_frame_from_arrays",
    "_build_ratio_metric_row",
    "_build_ratio_valid_mask",
    "_build_ratio_valid_mask_from_arrays",
    "_build_value_outlier_mask",
    "_compute_agg_ratio_diff_standard_error",
    "_compute_agg_ratio_group_stats",
    "_compute_agg_ratio_group_stats_arrays",
    "_compute_agg_ratio_variance",
    "_compute_bootstrap_family_max_statistics",
    "_compute_bootstrap_family_max_statistics_batch",
    "_compute_bootstrap_family_max_statistics_in_executor",
    "_compute_bootstrap_statistics",
    "_compute_bootstrap_statistics_batch",
    "_compute_bootstrap_statistics_in_executor",
    "_compute_outlier_cutoff",
    "_compute_cuped_p_value",
    "_compute_cuped_p_value_from_frame",
    "_compute_cuped_statistics",
    "_compute_cuped_statistics_from_frame",
    "_compute_group_diff_standard_error",
    "_compute_mean_delta_from_arrays",
    "_compute_mde_abs",
    "_compute_mde_from_standard_error",
    "_compute_metric_family_max_statistics_from_indices",
    "_compute_metric_family_statistics_from_indices",
    "_compute_metric_statistic_and_delta_from_indices",
    "_compute_metric_test_statistic_from_indices",
    "_compute_normal_p_value",
    "_compute_sample_variance",
    "_compute_studentized_statistic",
    "_compute_ttest_stat_and_p_value",
    "_compute_ttest_stat_and_p_value_arrays",
    "_count_outliers_by_group",
    "_get_numeric_metric_series",
    "_get_outlier_cutoff",
    "_normalize_ratio_metrics",
    "_prepare_bootstrap_context",
    "_require_ratio_spec_value",
    "_safe_mean",
    "_safe_relative",
    "_split_resamples_into_batches",
    "_extend_bootstrap_statistics",
    "_validate_input_columns",
    "_validate_mde_parameters",
    "_validate_multiple_comparisons_parameters",
    "_validate_outlier_parameters",
    "_validate_pre_experiment_dataframe",
    "_both_present",
]
